classimax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("postad.urls")),
    path("accounts/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("public/", include("publicprofile.urls")),
    path("friends/", include("friends.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postad/urls.py
from django.urls import path
from postad.views import *


app_name = "postad"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("adposts/", PostAdView.as_view(), name="adposts"),
    path("post/<int:pk>/<slug:slug>/", PostAdDetailView.as_view(), name="postad_detail"),
    path("create-postad/", PostAdCreateView.as_view(), name="create_postad"),
    path("update/<int:pk>/<slug:slug>/", UpdatePostAdView.as_view(), name="update_postad"),
    path("delete/<int:pk>/<slug:slug>", DeletePostAdView.as_view(), name="delete_adpost"),
    path("search-results/", SearchResultView.as_view(), name="search_results"),
    path("filter-results/", FilterResultView.as_view(), name="filter_results"),
    path("category/<int:pk>/<slug:slug>/", CategoryPostAdView.as_view(), name="category"),
    path("adposts/<str:city>/", CityAdPostListView.as_view(), name="city_adposts_list"),
    path("report/<int:pk>/", ReportAdCreateView.as_view(), name="report"),
    path("recent-visit-ads/", RecentVisitAdPostView.as_view(), name="recent_visit_ads"),
    path("trending-ads/", TrendingAdsViewList.as_view(), name="trending_ads"),
    path("following-users-ads/", FollowingUsersAdsListView.as_view(), name="following_users_ads"),
    path("about-us/", AboutUsView.as_view(), name="about_us"),
    path("terms-and-consitions/", TermsAndConditionsView.as_view(), name="terms_and_conditions"),
]

publicprofile/urls.py
from django.urls import path
from publicprofile.views import *

app_name = "publicprofile"

urlpatterns = [
    path("profile/<int:pk>/", PublicUserProfileView.as_view(), name="public_profile"),
    path("ad-posts/<int:pk>/", AdPostPublicView.as_view(), name="ad_posts"),
    path("contact/<int:pk>/", ContactAdUserView.as_view(), name="contact_ad_user"),
    path("following/<int:pk>/", FollowingsDetailView.as_view(), name="following"),
    path("followers/<int:pk>/", FollowersDetailView.as_view(), name="followers"),
    path("users/", UsersListView.as_view(), name="user_list")
]

postad/forms.py
from postad.models import *
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Field, Layout
from postad.models import Bookmark, ReportAdPost


class PostAdCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PostAdCreationForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.layout = Layout(
            Field("title", css_class="form-control bg-white"),
            Field("price", css_class="form-control bg-white"),
            Field("brand", css_class="form-control bg-white"),
            Field("model", css_class="form-control bg-white"),
            Field("state", css_class="form-control w-100 bg-white"),
            Field("city", css_class="form-control bg-white"),
            Field("purchase_year", css_class="form-control bg-white"),
            Field("category", css_class="form-control w-100 bg-white"),
            Field("condition", css_class="form-control w-100 bg-white"),
            Field("seller_type", css_class="form-control w-100 bg-white"),
            Field("description", css_class="form-control bg-white"),
            Field("image1", css_class="form-control bg-white"),
            Field("image2", css_class="form-control bg-white"),
            Field("image3", css_class="form-control bg-white"),
            Field("image4", css_class="form-control bg-white"),
            Field("image5", css_class="form-control bg-white"),
        )

        self.helper.add_input(Submit("submit", "Submit", css_class="btn btn-primary d-block mt-2"))
    
    class Meta:
        model = PostAD
        fields = [
            "title",
            "description",
            "price",
            "brand",
            "model",
            "purchase_year",
            "state",
            "city",
            "category",
            "condition",
            "seller_type",
            "image1",
            "image2",
            "image3",
            "image4",
            "image5",
        ]
        widgets = {
            "purchase_year": forms.DateInput(attrs={"type": "date"})
        }

class UpdatePostAdCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UpdatePostAdCreationForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.layout = Layout(
            Field("title", css_class="form-control bg-white"),
            Field("price", css_class="form-control bg-white"),
            Field("brand", css_class="form-control bg-white"),
            Field("model", css_class="form-control bg-white"),
            Field("state", css_class="form-control w-100 bg-white"),
            Field("city", css_class="form-control bg-white"),
            Field("purchase_year", css_class="form-control bg-white"),
            Field("category", css_class="form-control w-100 bg-white"),
            Field("condition", css_class="form-control w-100 bg-white"),
            Field("seller_type", css_class="form-control w-100 bg-white"),
            Field("description", css_class="form-control bg-white"),
            Field("image1", css_class="form-control bg-white"),
            Field("image2", css_class="form-control bg-white"),
            Field("image3", css_class="form-control bg-white"),
            Field("image4", css_class="form-control bg-white"),
            Field("image5", css_class="form-control bg-white"),
            Field("sold"),
        )

        self.helper.add_input(Submit("submit", "Submit", css_class="btn btn-primary d-block mt-2"))
    
    class Meta:
        model = PostAD
        fields = [
            "title",
            "description",
            "price",
            "brand",
            "model",
            "purchase_year",
            "state",
            "city",
            "category",
            "condition",
            "seller_type",
            "image1",
            "image2",
            "image3",
            "image4",
            "image5",
            "sold",
        ]
        widgets = {
            "purchase_year": forms.DateInput(attrs={"type": "date"})
        }


class BookmarkForm(forms.ModelForm):
    class Meta:
        model = Bookmark
        fields = "__all__"


class AdReportForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AdReportForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.layout = Layout(
            Field("subject", css_class="form-control w-100"),
            Field("comment", css_class="border w-100 p-3 mt-3 mt-lg-4"),
        )

        self.helper.add_input(Submit("submit", "Submit", css_class="btn btn-primary mt-2 float-right"))
    
    class Meta:
        model = ReportAdPost
        fields = [
            "subject",
            "comment",
        ]

postad/views.py
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from postad.models import PostAD, Bookmark, Category, ReportAdPost, RecentView
from django.db.models import F, Q
from postad.forms import PostAdCreationForm, BookmarkForm, UpdatePostAdCreationForm, AdReportForm
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormMixin
from django.db.models import F, Q
from friends.models import Follow



class IndexView(ListView):
    model = PostAD
    template_name = "postad/index.html"
    context_object_name = "postads"

    def get_queryset(self):
        return PostAD.objects.filter(sold=False).order_by("-id")[:4]
    
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context["trending_ads"] = PostAD.objects.filter(sold=False).order_by("-hits")[:4]
        
        if self.request.user.is_active:
            context["recent_visit"] = RecentView.objects.filter(user=self.request.user).order_by("-visit_date")[:4]

            #   get ads related only you following thoses users
            following_users_id = Follow.objects.filter(user=self.request.user).values("following")
            following_users_posts = []
            for post in following_users_id:
                following_users_posts.append(PostAD.objects.filter(user__id=post['following'], sold=False))
            ad_posts = []
            for post in following_users_posts:
                if len(post) > 0:
                    ad_posts.extend(post)
            ad_posts.sort(key = lambda x : -x.id)
            context["following_users_ads"] = ad_posts[:4]

        return context


class PostAdView(ListView):
    model = PostAD
    template_name = "postad/postsad.html"
    context_object_name = "posts"
    paginate_by = 9

    def get_queryset(self):
        return PostAD.objects.filter(sold=False).order_by("-id")
    
    def get_context_data(self, **kwargs):
        context = super(PostAdView, self).get_context_data(**kwargs)
        context["total_adpost"] = PostAD.objects.filter(sold=False).count()
        return context



class TrendingAdsViewList(ListView):
    model = PostAD
    template_name = "postad/trending-ads.html"
    context_object_name = "trending_ads"
    paginate_by = 9

    def get_queryset(self):
        return PostAD.objects.filter(sold=False).order_by("-hits")
    
    def get_context_data(self, **kwargs):
        context = super(TrendingAdsViewList, self).get_context_data(**kwargs)
        context["total_adpost"] = PostAD.objects.filter(sold=False).count()
        return context


class PostAdDetailView(LoginRequiredMixin, DetailView, FormMixin):
    model = PostAD
    template_name = "postad/postad-detail.html"
    context_object_name = "post"
    form_class = BookmarkForm

    def get_context_data(self, **kwargs):
        context = super(PostAdDetailView, self).get_context_data(**kwargs)
        context["bookmark"] = Bookmark.objects.filter(post=self.object.id, user=self.request.user)
        # context["similar_ad"] = PostAD.objects.filter(Q(category=self.object.category) | Q(condition=self.object.condition))
        context["similar_ad"] = PostAD.objects.filter(category=self.object.category)
        context["recent_visit"] = RecentView.objects.filter(user=self.request.user).order_by("-visit_date")[:4]
        return context

    def get(self, request, *args, **kwargs):
        self.hits = PostAD.objects.filter(id=self.kwargs["pk"]).update(hits=F("hits")+1)
        old_recent_ad_post = RecentView.objects.filter(user=self.request.user, post=PostAD.objects.get(id=self.kwargs["pk"]))

        if old_recent_ad_post:
            old_recent_ad_post.delete()
        
        RecentView.objects.create(user=self.request.user, post=PostAD.objects.get(id=self.kwargs["pk"]))

        return super(PostAdDetailView, self).get(request, *args, **kwargs)
    
    def form_valid(self, form):
        saved_adpost = Bookmark.objects.filter(user=self.request.user, post=self.object)
        if saved_adpost:
            saved_adpost.delete()
        else:
            Bookmark.objects.create(user=self.request.user, post=self.object)
        return super(PostAdDetailView, self).form_valid(form)
    
    def post(self, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy("postad:postad_detail", kwargs={"pk": self.object.id, "slug": self.object.slug})


class PostAdCreateView(LoginRequiredMixin, CreateView):
    model = PostAD
    form_class = PostAdCreationForm
    template_name = "postad/postad-create.html"
    context_object_name = "postad"

    def get_success_url(self):
        return reverse_lazy("postad:postad_detail", kwargs={"pk":self.object.id, "slug":self.object.slug})
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        
        return super(PostAdCreateView, self).form_valid(form)


class UpdatePostAdView(LoginRequiredMixin, UpdateView):
    model = PostAD
    template_name = "postad/update-postad.html"
    form_class = UpdatePostAdCreationForm

    def get_success_url(self):
        return reverse_lazy("postad:postad_detail", kwargs={"pk": self.object.id, "slug": self.object.slug})
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(UpdatePostAdView, self).form_valid(form)
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user != request.user:
            return HttpResponseRedirect("/")
        return super(UpdatePostAdView, self).get(request, *args, **kwargs)


class DeletePostAdView(LoginRequiredMixin, DeleteView):
    model = PostAD
    success_url = reverse_lazy("postad:adposts")
    template_name = "postad/delete-postad.html"

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.user == request.user:
            self.object.delete()
            return HttpResponseRedirect(self.success_url)
        return HttpResponseRedirect(self.success_url)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user != request.user:
            return HttpResponseRedirect("/")
        return super(DeletePostAdView, self).get(request, *args, **kwargs)


class SearchResultView(ListView):
    model = PostAD
    template_name = "postad/search-results.html"
    context_object_name = "posts"
    paginate_by = 9

    def get_queryset(self):
        query = self.request.GET.get("q")
        category = self.request.GET.get("category")
        location = self.request.GET.get("location")

        if query != '' and category != '' and location != '':
            return PostAD.objects.filter(Q(title__icontains=query) | Q(description__icontains=query)).filter(category__title__icontains=category).filter(city__icontains=location).filter(sold=False).order_by("-id").distinct()

        elif query != '' and category != '' and location == '':
            return PostAD.objects.filter(Q(title__icontains=query) | Q(description__icontains=query)).filter(category__title__icontains=category).filter(sold=False).order_by("-id").distinct()
            
        elif query != '' and category == '' and location != '':
            return PostAD.objects.filter(Q(title__icontains=query) | Q(description__icontains=query)).filter(city__icontains=location).filter(sold=False).order_by("-id").distinct()
        
        elif query == '' and category == '' and location != '':
            return PostAD.objects.filter(Q(title__icontains=query) | Q(description__icontains=query)).filter(city__icontains=location).filter(sold=False).order_by("-id").distinct()
        
        elif query == '' and category != '' and location == '':
            return PostAD.objects.filter(Q(title__icontains=query) | Q(description__icontains=query)).filter(category__title__icontains=category).filter(sold=False).order_by("-id").distinct()

        elif query != '':
            return PostAD.objects.filter(Q(title__icontains=query) | Q(description__icontains=query)).filter(sold=False).order_by("-id").distinct()
        
        return PostAD.objects.filter(sold=False).order_by("-id")


class CategoryPostAdView(ListView):
    model = PostAD
    template_name = "filter/categories-list.html"
    context_object_name = "categories"

    def get_context_data(self, **kwargs):
        context = super(CategoryPostAdView, self).get_context_data(**kwargs)
        context["posts"] = PostAD.objects.filter(category__id=self.kwargs["pk"], sold=False)
        context["total_posts"] = PostAD.objects.filter(category__id=self.kwargs["pk"], sold=False).count()
        # context["category_title"] = PostAD.objects.filter(category__id=self.kwargs["pk"])[0]
        context["category_name"] = Category.objects.get(pk=self.kwargs["pk"])
        return context




class FilterResultView(ListView):
    model = PostAD
    template_name = "filter/filter-results.html"
    context_object_name = "posts"
    paginate_by = 9

    def get_queryset(self):
        short = self.request.GET.get("short")
        condition = self.request.GET.get("condition")
        price = self.request.GET.get("price")

        #   if condition, price and short is there
        if condition and price and short:
            min_price = price.split(",")[0]
            max_price = price.split(",")[1]

            if short == "Popularity":
                return PostAD.objects.filter(condition=condition).filter(price__gte=min_price, price__lte=max_price).filter(sold=False).order_by("-hits")
            elif short == "LowestPrice":

templates/postad/delete-postad.html
{% extends "base.html" %}
<!--  -->
{% load crispy_forms_tags %}
<!--  -->

{% block content %}

<section class="advt-post bg-gray py-5">
  <div class="container">
    <div class="row bg-white p-5">
      <div class="col-lg-8">
        <h2>Are you sure to delete this Ad Post ?</h2>
        <p>Once you delete your Ad Post then you can not recover.</p>
        <form method="post">
          {% csrf_token %}

          <button type="submit" class="btn btn-primary d-block mt-2">Confirm</button>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/postad/following-users-ads.html
{% extends 'base.html' %}
<!--  -->
{% load static %}
<!--  -->

{% load custom_tags %}

<!--  -->

{% load humanize %}

<!--  -->

{% block content %}

<!-- serach -->
<section class="page-search">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="advance-search nice-select-white">
          <form action="{% url 'postad:search_results' %}" method="GET">
            <div class="form-row align-items-center">
              <div class="form-group col-xl-4 col-lg-3 col-md-6">
                <input type="text" name="q" class="form-control my-2 my-lg-0" id="inputtext4" placeholder="What are you looking for" />
              </div>
              <div class="form-group col-lg-3 col-md-6">
                <select class="w-100 form-control my-2 my-lg-0" name="category">
                  <option value="">Select</option>
                  {% categories as categories %}
                  <!--  -->
                  {% for category in categories %}
                  <option value="{{category}}">{{category}}</option>
                  {% endfor %}
                </select>
              </div>
              <div class="form-group col-lg-3 col-md-6">
                <input type="text" name="location" class="form-control my-2 my-lg-0" id="inputLocation4" placeholder="Location" />
              </div>
              <div class="form-group col-xl-2 col-lg-3 col-md-6">
                <button type="submit" class="btn btn-primary active w-100">Search Now</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- end serach -->

<section class="section-sm">
  <div style="width: 85%; margin: auto">
    <div class="row">
      <div class="col-lg-3 col-md-4">{% include 'includes/left-filter-sidebar.html' %}</div>

      <div class="col-lg-9 col-md-8">
        <div class="category-search-filter">
          <div class="row">
            <div class="col-md-6 text-center text-md-left mt-2">
              <!-- <h5>Showing your following users ads results</h5> -->
              <h5>{{postads|length}} Ads Found Your Following Users Related</h5>
            </div>
            <div class="col-md-6 text-center text-md-right mt-2 mt-md-0">
              <div class="view">
                <strong>Views</strong>
                <ul class="list-inline view-switcher">
                  <li class="list-inline-item">
                    <a href="" onclick="event.preventDefault();" class="text-info"><i class="fa fa-th-large"></i></a>
                  </li>
                  <li class="list-inline-item">
                    <a href=""><i class="fa fa-reorder"></i></a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- ad listing list  -->
        {% for post in postads %}
        <div class="ad-listing-list mt-20">
          <div class="row p-lg-3 p-sm-5 p-4">
            <div class="col-lg-4 align-self-center">
              <a href="{% url 'postad:postad_detail' pk=post.id slug=post.slug %}">
                <img src="{{post.image1.url}}" class="img-fluid" alt="" style="width: 100%; height: 275px" />
              </a>
            </div>
            <div class="col-lg-8 mt-2">
              <div class="row">
                <div class="col-lg-8 col-md-10">
                  <div class="ad-listing-content">
                    <h2>
                      <a href="{% url 'postad:postad_detail' pk=post.id slug=post.slug %}" class="font-weight-bold">{{post.title}}</a>
                    </h2>

                    <!--  -->
                    <ul class="list-inline mt-3 mb-3">
                      <!-- author -->
                      <li class="list-inline-item mb-1">
                        <a href="{% url 'publicprofile:public_profile' pk=post.user.id %}" style="color: gray">
                          <i class="fa fa-user" aria-hidden="true"></i> Author -
                          <span style="color: gray; font-weight: bold">{{post.user.first_name}} {{post.user.last_name}}</span>
                        </a>
                      </li>
                      <br />

                      <!-- category -->
                      <li class="list-inline-item mb-1">
                        <a href="{% url 'postad:category' pk=post.category.id slug=post.category.slug %}" style="color: gray">
                          <i class="fa fa-folder-open-o"></i> Category -
                          <span style="color: gray; font-weight: bold">{{post.category.title}}</span>
                        </a>
                      </li>
                      <br />

                      <!-- location -->
                      <li class="list-inline-item mb-1">
                        <a href="{% url 'postad:city_adposts_list' city=post.city %}" style="color: gray">
                          <i class="fa fa-map-marker" aria-hidden="true"></i> Location -
                          <span style="color: gray; font-weight: bold">{{post.city}}, {{post.state}}</span>
                        </a>
                      </li>
                      <br />

                      <!-- views -->
                      <li class="list-inline-item mb-1">
                        <span style="color: gray">
                          <i class="fa fa-eye" aria-hidden="true"></i> Views - <span style="color: gray; font-weight: bold">{{post.hits}}</span>
                        </span>
                      </li>
                      <br />

                      <!-- date -->
                      <li class="list-inline-item mb-1">
                        <span style="color: gray">
                          <i class="fa fa-calendar"></i> Publish Date -
                          <span style="color: gray; font-weight: bold">{{post.publish_date|date:"d-M-o"}}</span>
                        </span>
                      </li>
                    </ul>
                    <!--  -->
                  </div>
                </div>
                <div class="col-lg-4 align-self-center">
                  <div class="product-ratings" style="color: rgb(6, 55, 120); font-weight: bold">Price : ₹ {{post.price|intcomma}}</div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        <!-- ad listing list  -->

        <!-- pagination -->
        <div class="mt-5">{% include "includes/pagination.html" %}</div>
        <!-- end pagination -->
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/postad/recent-visit-ads.html
{% extends 'base.html' %}
<!--  -->
{% load static %}
<!--  -->

{% load custom_tags %}

<!--  -->

{% load humanize %}

<!--  -->

{% block content %}

<!-- serach -->
<section class="page-search">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="advance-search nice-select-white">
          <form action="{% url 'postad:search_results' %}" method="GET">
            <div class="form-row align-items-center">
              <div class="form-group col-xl-4 col-lg-3 col-md-6">
                <input type="text" name="q" class="form-control my-2 my-lg-0" id="inputtext4" placeholder="What are you looking for" />
              </div>
              <div class="form-group col-lg-3 col-md-6">
                <select class="w-100 form-control my-2 my-lg-0" name="category">
                  <option value="">Select</option>
                  {% categories as categories %}
                  <!--  -->
                  {% for category in categories %}
                  <option value="{{category}}">{{category}}</option>
                  {% endfor %}
                </select>
              </div>
              <div class="form-group col-lg-3 col-md-6">
                <input type="text" name="location" class="form-control my-2 my-lg-0" id="inputLocation4" placeholder="Location" />
              </div>
              <div class="form-group col-xl-2 col-lg-3 col-md-6">
                <button type="submit" class="btn btn-primary active w-100">Search Now</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- end serach -->

<section class="section-sm">
  <div style="width: 85%; margin: auto">
    <div class="row">
      <div class="col-lg-3 col-md-4">{% include 'includes/left-filter-sidebar.html' %}</div>

      <div class="col-lg-9 col-md-8">
        <div class="category-search-filter">
          <div class="row">
            <div class="col-md-6 text-center text-md-left mt-2">
              <h5>Showing {{total_adpost}} recent visit ads results</h5>
            </div>
            <div class="col-md-6 text-center text-md-right mt-2 mt-md-0">
              <div class="view">
                <strong>Views</strong>
                <ul class="list-inline view-switcher">
                  <li class="list-inline-item">
                    <a href="" onclick="event.preventDefault();" class="text-info"><i class="fa fa-th-large"></i></a>
                  </li>
                  <li class="list-inline-item">
                    <a href=""><i class="fa fa-reorder"></i></a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- ad listing list  -->

        {% for post in posts %}
        <div class="ad-listing-list mt-20">
          <div class="row p-lg-3 p-sm-5 p-4">
            <div class="col-lg-4 align-self-center">
              <a href="{% url 'postad:postad_detail' pk=post.post.id slug=post.post.slug %}">
                <img src="{{post.post.image1.url}}" class="img-fluid" alt="" style="width: 100%; height: 275px" />
              </a>
            </div>
            <div class="col-lg-8 mt-2">
              <div class="row">
                <div class="col-lg-8 col-md-10">
                  <div class="ad-listing-content">
                    <h2>
                      <a href="{% url 'postad:postad_detail' pk=post.post.id slug=post.post.slug %}" class="font-weight-bold">{{post.post.title}}</a>
                    </h2>

                    <!--  -->
                    <ul class="list-inline mt-3 mb-3">
                      <li class="list-inline-item mb-1">
                        <a href="{% url 'postad:category' pk=post.post.category.id slug=post.post.category.slug %}" style="color: gray">
                          <i class="fa fa-folder-open-o"></i> Category -
                          <span style="color: gray; font-weight: bold">{{post.post.category.title}}</span>
                        </a>
                      </li>
                      <br />
                      <li class="list-inline-item mb-1">
                        <a href="#" style="color: gray">
                          <i class="fa fa-calendar"></i> Recent Visit -
                          <span style="color: gray; font-weight: bold">{{post.visit_date|date:"d-M-o"}}</span>
                        </a>
                      </li>
                      <br />
                      <li class="list-inline-item mb-1">
                        <a href="#" style="color: gray">
                          <i class="fa fa-eye" aria-hidden="true"></i> Views - <span style="color: gray; font-weight: bold">{{post.post.hits}}</span>
                        </a>
                      </li>
                      <br />
                      <li class="list-inline-item mb-1">
                        <a href="{% url 'postad:city_adposts_list' city=post.post.city %}" style="color: gray">
                          <i class="fa fa-map-marker" aria-hidden="true"></i> Location -
                          <span style="color: gray; font-weight: bold">{{post.post.city}}, {{post.post.state}}</span>
                        </a>
                      </li>
                    </ul>
                    <!--  -->
                  </div>
                </div>
                <div class="col-lg-4 align-self-center">
                  <div class="product-ratings" style="color: rgb(6, 55, 120); font-weight: bold">Price : ₹ {{post.post.price|intcomma}}</div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        <!-- ad listing list  -->

        <!-- pagination -->
        <div class="mt-5">{% include "includes/pagination.html" %}</div>
        <!-- end pagination -->
      </div>
    </div>
  </div>
</section>

{% endblock %}