accounts/urls.py
from django.urls import path
from accounts.views import *


app_name = "accounts"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginUserView.as_view(), name="login"),
    path("logout/", LogoutUserView.as_view(), name="logout"),
]

classimax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("postad.urls")),
    path("accounts/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("public/", include("publicprofile.urls")),
    path("friends/", include("friends.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from dashboard.views import *
from friends.views import *


app_name = "dashboard"

urlpatterns = [
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("update-profile/<int:pk>/", UpdateUserProfile.as_view(), name="update_profile"),
    path("my-ad-posts/", MyAdPostView.as_view(), name="my_adposts"),
    path("bookmarks/", BookmarkAdPostView.as_view(), name="bookmark_adposts"),
    path("contacts/", ContactUserView.as_view(), name="user_contacts"),
    path("send-contact/", SendContactView.as_view(), name="send_contact"),
    path("following/", FollowingsListView.as_view(), name="following"),
    path("followers/", FollowersListView.as_view(), name="followers")

]

postad/urls.py
from django.urls import path
from postad.views import *


app_name = "postad"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("adposts/", PostAdView.as_view(), name="adposts"),
    path("post/<int:pk>/<slug:slug>/", PostAdDetailView.as_view(), name="postad_detail"),
    path("create-postad/", PostAdCreateView.as_view(), name="create_postad"),
    path("update/<int:pk>/<slug:slug>/", UpdatePostAdView.as_view(), name="update_postad"),
    path("delete/<int:pk>/<slug:slug>", DeletePostAdView.as_view(), name="delete_adpost"),
    path("search-results/", SearchResultView.as_view(), name="search_results"),
    path("filter-results/", FilterResultView.as_view(), name="filter_results"),
    path("category/<int:pk>/<slug:slug>/", CategoryPostAdView.as_view(), name="category"),
    path("adposts/<str:city>/", CityAdPostListView.as_view(), name="city_adposts_list"),
    path("report/<int:pk>/", ReportAdCreateView.as_view(), name="report"),
    path("recent-visit-ads/", RecentVisitAdPostView.as_view(), name="recent_visit_ads"),
    path("trending-ads/", TrendingAdsViewList.as_view(), name="trending_ads"),
    path("following-users-ads/", FollowingUsersAdsListView.as_view(), name="following_users_ads"),
    path("about-us/", AboutUsView.as_view(), name="about_us"),
    path("terms-and-consitions/", TermsAndConditionsView.as_view(), name="terms_and_conditions"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.conf import settings



class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError("User must have an email address")
        
        if not username:
            raise ValueError("User must have an username")
        
        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, username, email, password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
            password = password
        )

        user.is_admin = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)



class Account(AbstractBaseUser):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    username = models.CharField(max_length=200, unique=True)
    email = models.CharField(max_length=300, unique=True)
    phone = models.CharField(max_length=50, null=True, blank=True)
    about = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to="users/profile/", default="users/default.png")
    dob = models.DateField(null=True, blank=True)

    GENDER_TYPE_LIST = [
        ("Male", "Male"),
        ("Female", "Female"),
        ("Other", "Other"),
    ]

    gender = models.CharField(max_length=10, choices=GENDER_TYPE_LIST, null=True, blank=True)

    #   required
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = MyAccountManager()


    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, add_label):
        return True


class ContactUser(models.Model):
    sender_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="sender_user")
    receiver_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="receiver_user")
    subject = models.CharField(max_length=150)
    message = models.TextField()
    review = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.sender_user} - {self.receiver_user} - {self.subject}"

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Field, Layout
from accounts.models import ContactUser
from django.contrib.auth import get_user_model
User = get_user_model()


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=200)
    last_name = forms.CharField(max_length=200)
    username = forms.CharField(max_length=200)
    email = forms.EmailField(max_length=200)
    password1 = forms.CharField()
    password2 = forms.CharField()

    class Meta(UserCreationForm):
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")



class UserProfileUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserProfileUpdateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.layout = Layout(
            Field("username", css_class="form-control bg-white"),
            Field("first_name", css_class="form-control bg-white"),
            Field("last_name", css_class="form-control bg-white"),
            Field("email", css_class="form-control bg-white"),
            Field("phone", css_class="form-control bg-white"),
            Field("about", css_class="form-control bg-white"),
            Field("dob", css_class="form-control bg-white"),
            Field("gender", css_class="form-control w-100 bg-white"),
            Field("image", css_class="form-control bg-white"),
        )

        self.helper.add_input(Submit("submit", "Submit", css_class="btn btn-primary d-block mt-2"))
    
    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "phone",
            "about",
            "dob",
            "gender",
            "image"  
        ]
        widgets = {
            "dob": forms.DateInput(attrs={"type": "date"})
        }


class CreateContactForm(forms.ModelForm):
    class Meta:
        model = ContactUser
        fields = ["review"]

accounts/views.py
from django.views.generic import TemplateView, CreateView, DetailView, ListView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.forms import RegisterForm, UserProfileUpdateForm, CreateContactForm
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User
from django.conf import settings
from accounts.models import Account, ContactUser
from postad.models import PostAD, Bookmark
from django.contrib.auth import get_user_model
User = get_user_model()



class RegisterView(CreateView):
    template_name = "accounts/register.html"
    form_class = RegisterForm
    success_url = reverse_lazy("accounts:login")

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect("/")
        return super(RegisterView, self).dispatch(request, *args, **kwargs)


class LoginUserView(LoginView):
    template_name = "accounts/login.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect("/")
        return super(LoginUserView, self).dispatch(request, *args, **kwargs)


class LogoutUserView(LogoutView):
    template_name = "accounts/register.html"

templates/accounts/login.html
{% extends 'base.html' %}

<!--  -->

{% block content %}

<section class="login py-5 border-top-1">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-5 col-md-8 align-item-center">
        <div class="border">
          <h3 class="bg-gray p-4">Login Now</h3>
          <form action="" method="post">
            {% csrf_token %}

            <!-- errors  -->
            {% if form.errors %}
            <div class="alert alert-danger m-2" role="alert">
              <h4 style="color: red; font-weight: 900">Please correct the errors below</h4>
              <ul>
                {% for field in form %}
                <!--  -->
                {% if field.errors %}
                <li>{{field.label}} : {{field.errors|striptags}}</li>
                {% endif %}
                <!--  -->
                {% endfor %}
              </ul>
            </div>
            {% endif %}
            <!-- end errors  -->

            <fieldset class="p-4">
              <!-- email -->
              <input class="form-control mb-3" type="email" name="username" placeholder="Email" required />

              <!-- password -->
              <input class="form-control mb-3" type="password" name="password" placeholder="Password" required />

              <button type="submit" class="btn btn-primary font-weight-bold mt-3">Log in</button>

              <a class="mt-3 d-block text-primary" href="#!">Forget Password?</a>
              <a class="mt-3 d-inline-block text-primary" href="{% url 'accounts:register' %}">Register Now</a>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}
<!--  -->
<!--  -->

{% block content %}

<section class="dashboard section">
  <!-- Container Start -->
  <div class="container">
    <!-- <div style="width: 90%; margin: auto"> -->
    <!-- Row Start -->
    <div class="row">
      <div class="col-lg-4">
        <div class="sidebar">
          <!-- User Widget -->
          <div class="widget user-dashboard-profile">
            <!-- User Image -->
            <div class="profile-thumb">
              <img src="{{profile.image.url}}" alt="" class="rounded-circle" />
            </div>
            <!-- User Name -->
            <h5 class="text-center">{{profile.first_name}} {{profile.last_name}}</h5>
            <p>Joined {{profile.date_joined|date:"d M o"}}</p>
            <a href="user-profile.html" class="btn btn-main-sm">Edit Profile</a>
          </div>
          <!-- Dashboard Links -->
          <div class="widget user-dashboard-menu">
            <ul>
              <li class="active">
                <a href="{% url 'accounts:profile' %}"><i class="fa fa-user"></i>Profile</a>
              </li>
              <li>
                <a href="dashboard-my-ads.html"><i class="fa fa-user"></i> My Ads</a>
              </li>
              <li>
                <a href="dashboard-favourite-ads.html"><i class="fa fa-bookmark-o"></i> Favourite Ads <span>5</span></a>
              </li>
              <li>
                <a href="dashboard-archived-ads.html"><i class="fa fa-file-archive-o"></i>Archeved Ads <span>12</span></a>
              </li>
              <li>
                <a href="dashboard-pending-ads.html"><i class="fa fa-bolt"></i> Pending Approval<span>23</span></a>
              </li>
              <li>
                <a href="index.html"><i class="fa fa-cog"></i> Logout</a>
              </li>
              <li>
                <a href="#!" data-toggle="modal" data-target="#deleteaccount"><i class="fa fa-power-off"></i>Delete Account</a>
              </li>
            </ul>
          </div>

          <!-- delete-account modal -->
          <!-- delete account popup modal start-->
          <!-- Modal -->
          <div class="modal fade" id="deleteaccount" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header border-bottom-0">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body text-center">
                  <img src="images/account/Account1.png" class="img-fluid mb-2" alt="" />
                  <h6 class="py-2">Are you sure you want to delete your account?</h6>
                  <p>Do you really want to delete these records? This process cannot be undone.</p>
                  <textarea class="form-control" name="message" id="" cols="40" rows="4" class="w-100 rounded"></textarea>
                </div>
                <div class="modal-footer border-top-0 mb-3 mx-5 justify-content-center">
                  <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                  <button type="button" class="btn btn-danger">Delete</button>
                </div>
              </div>
            </div>
          </div>
          <!-- delete account popup modal end-->
          <!-- delete-account modal -->
        </div>
      </div>
      <div class="col-lg-8">
        <!-- Edit Profile Welcome Text -->
        <div class="widget welcome-message">
          <h2>Public Profile</h2>
        </div>
        <!-- Edit Personal Info -->

        <!-- profile info -->
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="widget personal-info">
              <h4 class="widget-header user">Edit Personal Information</h4>
              <p><strong style="color: black">USERNAME : </strong> {{profile.username}}</p>
              <p><strong style="color: black">FIRST_NAME : </strong> {{profile.first_name}}</p>
              <p><strong style="color: black">LAST NAME : </strong> {{profile.last_name}}</p>
              <p><strong style="color: black">EMAIL : </strong> {{profile.email}}</p>
              <p><strong style="color: black">PHONE : </strong> {{profile.phone}}</p>
              <p><strong style="color: black">DATE OF BIRTH : </strong> {{profile.dob}}</p>
              <p><strong style="color: black">GENDER : </strong> {{profile.gender}}</p>
              <p><strong style="color: black">DATE JOINED : </strong> {{profile.date_joined|date:"d M o"}}</p>
            </div>
          </div>
        </div>
        <!-- end profile info -->
      </div>
    </div>
    <!-- Row End -->
  </div>
  <!-- Container End -->
</section>

{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}

<!--  -->

{% block content %}

<section class="login py-5 border-top-1">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-7 col-md-8 align-item-center">
        <div class="border border">
          <h3 class="bg-gray p-4">Create New Account</h3>
          <form action="" method="post">
            {% csrf_token %}
            <!-- errors  -->
            {% if form.errors %}
            <div class="alert alert-danger m-2" role="alert">
              <h4 style="color: red; font-weight: 900">Please correct the errors below</h4>
              <ul>
                {% for field in form %}
                <!--  -->
                {% if field.errors %}
                <li>{{field.label}} : {{field.errors|striptags}}</li>
                {% endif %}
                <!--  -->
                {% endfor %}
              </ul>
            </div>
            {% endif %}
            <!-- end errors  -->

            <fieldset class="p-4">
              <div class="row">
                <div class="col-md-6">
                  <!-- first name -->
                  <input class="form-control mb-3" type="text" name="first_name" placeholder="First Name" required />
                </div>

                <div class="col-md-6">
                  <!-- last name -->
                  <input class="form-control mb-3" type="text" name="last_name" placeholder="Last Name" required />
                </div>
              </div>

              <!-- username -->
              <input class="form-control mb-3" type="text" name="username" placeholder="Username" required />

              <!-- email -->
              <input class="form-control mb-3" type="email" name="email" placeholder="Email" required />

              <!-- password -->
              <input class="form-control mb-3" name="password1" type="password" placeholder="Password" required />

              <!-- confirm password -->
              <input class="form-control mb-3" type="password" name="password2" placeholder="Confirm Password" required />
              <button type="submit" class="btn btn-primary font-weight-bold mt-3">Register</button>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}