accounts/urls.py
from django.urls import path
from accounts.views import *


app_name = "accounts"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginUserView.as_view(), name="login"),
    path("logout/", LogoutUserView.as_view(), name="logout"),
]

classimax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("postad.urls")),
    path("accounts/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("public/", include("publicprofile.urls")),
    path("friends/", include("friends.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from dashboard.views import *
from friends.views import *


app_name = "dashboard"

urlpatterns = [
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("update-profile/<int:pk>/", UpdateUserProfile.as_view(), name="update_profile"),
    path("my-ad-posts/", MyAdPostView.as_view(), name="my_adposts"),
    path("bookmarks/", BookmarkAdPostView.as_view(), name="bookmark_adposts"),
    path("contacts/", ContactUserView.as_view(), name="user_contacts"),
    path("send-contact/", SendContactView.as_view(), name="send_contact"),
    path("following/", FollowingsListView.as_view(), name="following"),
    path("followers/", FollowersListView.as_view(), name="followers")

]

postad/urls.py
from django.urls import path
from postad.views import *


app_name = "postad"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("adposts/", PostAdView.as_view(), name="adposts"),
    path("post/<int:pk>/<slug:slug>/", PostAdDetailView.as_view(), name="postad_detail"),
    path("create-postad/", PostAdCreateView.as_view(), name="create_postad"),
    path("update/<int:pk>/<slug:slug>/", UpdatePostAdView.as_view(), name="update_postad"),
    path("delete/<int:pk>/<slug:slug>", DeletePostAdView.as_view(), name="delete_adpost"),
    path("search-results/", SearchResultView.as_view(), name="search_results"),
    path("filter-results/", FilterResultView.as_view(), name="filter_results"),
    path("category/<int:pk>/<slug:slug>/", CategoryPostAdView.as_view(), name="category"),
    path("adposts/<str:city>/", CityAdPostListView.as_view(), name="city_adposts_list"),
    path("report/<int:pk>/", ReportAdCreateView.as_view(), name="report"),
    path("recent-visit-ads/", RecentVisitAdPostView.as_view(), name="recent_visit_ads"),
    path("trending-ads/", TrendingAdsViewList.as_view(), name="trending_ads"),
    path("following-users-ads/", FollowingUsersAdsListView.as_view(), name="following_users_ads"),
    path("about-us/", AboutUsView.as_view(), name="about_us"),
    path("terms-and-consitions/", TermsAndConditionsView.as_view(), name="terms_and_conditions"),
]

publicprofile/urls.py
from django.urls import path
from publicprofile.views import *

app_name = "publicprofile"

urlpatterns = [
    path("profile/<int:pk>/", PublicUserProfileView.as_view(), name="public_profile"),
    path("ad-posts/<int:pk>/", AdPostPublicView.as_view(), name="ad_posts"),
    path("contact/<int:pk>/", ContactAdUserView.as_view(), name="contact_ad_user"),
    path("following/<int:pk>/", FollowingsDetailView.as_view(), name="following"),
    path("followers/<int:pk>/", FollowersDetailView.as_view(), name="followers"),
    path("users/", UsersListView.as_view(), name="user_list")
]

templates/includes/adposts-loop.html
{% load humanize %}
<!--  -->

<!-- if post not exists -->
{% if posts %}

<!--  -->
{% for post in posts %}
<div class="col-lg-4 col-md-6">
  <div class="product-item bg-light">
    <div class="card">
      <div class="thumb-content">
        <!-- <div class="price">$200</div> -->
        <a href="{% url 'postad:postad_detail' pk=post.id slug=post.slug %}">
          <img class="card-img-top img-fluid" src="{{post.image1.url}}" style="width: 100%; height: 275px" alt="Card image cap" />
        </a>
      </div>
      <div class="card-body">
        <h4 class="card-title"><a href="{% url 'postad:postad_detail' pk=post.id slug=post.slug %}">{{post.title}}</a></h4>
        <ul class="list-inline product-meta">
          <li class="list-inline-item">
            <a href="{% url 'postad:category' pk=post.category.id slug=post.category.slug %}">
              <i class="fa fa-folder-open-o"></i>Category - <span style="color: gray; font-weight: bold">{{post.category.title}}</span>
            </a>
          </li>
          <br />
          <li class="list-inline-item">
            <a href="#">
              <i class="fa fa-calendar"></i>Publish Date -
              <span style="color: gray; font-weight: bold">{{post.publish_date|date:"d-M-o"}}</span>
            </a>
          </li>
          <br />
          <li class="list-inline-item">
            <a href="#"> <i class="fa fa-eye" aria-hidden="true"></i>Views - <span style="color: gray; font-weight: bold">{{post.hits}}</span> </a>
          </li>
          <br />
          <li class="list-inline-item">
            <a href="#">
              <i class="fa fa-map-marker" aria-hidden="true"></i>Location -
              <span style="color: gray; font-weight: bold">{{post.city}}, {{post.state}}</span>
            </a>
          </li>
        </ul>
        <div class="product-ratings" style="color: rgb(6, 55, 120); font-weight: bold">Price : ₹ {{post.price|intcomma}}</div>
      </div>
    </div>
  </div>
</div>
{% endfor %}

<!--  -->

{% else %}

<h1>SORRY, no results found</h1>

<!--  -->
{% endif %}

templates/includes/footer.html
{% load static %}

<footer class="footer section section-sm">
  <div class="container">
    <div class="row">
      <!-- about -->
      <div class="col-lg-3 col-md-7 offset-md-1 offset-lg-0 mb-4 mb-lg-0">
        <div class="block about">
          <img src="{% static 'images/logo-footer.png' %}" alt="logo" />
          <p class="alt-color">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
            minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
          </p>
        </div>
      </div>
      <!-- end about -->

      <!-- top navbar menus -->
      <div class="col-lg-2 offset-lg-1 col-md-3 col-6 mb-4 mb-lg-0">
        <div class="block">
          <h4>Site Pages</h4>
          <ul>
            <li><a href="{% url 'postad:index' %}">Home</a></li>
            <li>
              <a href="{% url 'postad:adposts' %}">Explore Ads</a>
            </li>
            <li><a href="{% url 'postad:trending_ads' %}">Trending Ads</a></li>
            <li><a href="{% url 'postad:terms_and_conditions' %}">Terms & Conditions</a></li>
            <li><a href="{% url 'postad:about_us' %}">About Us</a></li>
          </ul>
        </div>
      </div>
      <!-- end top navbar menus -->

      <!-- Dashboard -->
      <div class="col-lg-2 col-md-3 offset-md-1 offset-lg-0 col-6 mb-4 mb-md-0">
        <div class="block">
          <h4>Dashboard</h4>
          <ul>
            <li><a href="{% url 'dashboard:profile' %}">Profile</a></li>
            <li><a href="{% url 'dashboard:followers' %}">Followers</a></li>
            <li><a href="{% url 'dashboard:following' %}">Following</a></li>
            <li><a href="{% url 'dashboard:my_adposts' %}">My Ads</a></li>
            <li><a href="{% url 'dashboard:bookmark_adposts' %}">Favourite Ads</a></li>
            <li><a href="{% url 'dashboard:user_contacts' %}">Contacts</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          </ul>
        </div>
      </div>
      <!-- Dashboard -->

      <!-- Promotion -->
      <div class="col-lg-4 col-md-7">
        <div class="block-2 app-promotion">
          <div class="mobile d-flex align-items-center">
            <a href="{% url 'postad:index' %}">
              <img src="{% static 'images/footer/phone-icon.png' %}" alt="mobile-icon" />
            </a>
            <p class="mb-0">Get the Dealsy Mobile App and Save more</p>
          </div>
          <div class="download-btn d-flex my-3">
            <a href="{% url 'postad:index' %}"><img src="{% static 'images/apps/google-play-store.png' %}" class="img-fluid" alt="" /></a>
            <a href="{% url 'postad:index' %}" class="ml-3"><img src="{% static 'images/apps/apple-app-store.png' %}" class="img-fluid" alt="" /></a>
          </div>
        </div>
      </div>
      <!-- end Promotion -->
    </div>
  </div>
</footer>

<!-- Footer Bottom -->
<footer class="footer-bottom">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 text-center text-lg-left mb-3 mb-lg-0">
        <div class="copyright">
          <p>
            Copyright &copy;
            <script>
              var CurrentYear = new Date().getFullYear();
              document.write(CurrentYear);
            </script>
            . Designed & Developed by
            <a class="text-white" href="https://www.linkedin.com/in/kingarunesh/">Arunesh kumar</a>
          </p>
        </div>
      </div>
      <div class="col-lg-6">
        <!-- Social Icons -->
        <ul class="social-media-icons text-center text-lg-right">
          <li>
            <a class="fa fa-facebook" href="https://www.facebook.com/themefisher"></a>
          </li>
          <li>
            <a class="fa fa-twitter" href="https://www.twitter.com/themefisher"></a>
          </li>
          <li>
            <a class="fa fa-pinterest-p" href="https://www.pinterest.com/themefisher"></a>
          </li>
          <li>
            <a class="fa fa-github-alt" href="https://www.github.com/themefisher"></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <!-- Container End -->
  <!-- To Top -->
  <div class="scroll-top-to">
    <i class="fa fa-angle-up"></i>
  </div>
</footer>

templates/includes/header.html
{% load static %}

<!--  -->

{% load custom_tags %}

<!--  -->

<header>
  <!-- <div class="container"> -->
  <div style="width: 90%; margin: auto">
    <div class="row">
      <div class="col-md-12">
        <nav class="navbar navbar-expand-lg navbar-light navigation">
          <a class="navbar-brand" href="{% url 'postad:index' %}">
            <img src="{% static 'images/logo.png' %}" alt="" />
          </a>
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- main menu -->
            <ul class="navbar-nav ml-auto main-nav">
                <!-- home -->
              <li 
              {% if '/' == request.path %}
                    class="nav-item active"
                {% else %}
                    class="nav-item"
                {% endif %}
              >
                <a class="nav-link" href="{% url 'postad:index' %}"><i class="fa fa-home" aria-hidden="true"></i> Home</a>
              </li>

              <!-- ads -->
              <li 
              {% if 'adposts' in request.path %}
                    class="nav-item active"
                {% else %}
                    class="nav-item"
                {% endif %}
              >
                <a class="nav-link" href="{% url 'postad:adposts' %}"><i class="bi bi-airplane-fill"></i> Explore Ads</a>
              </li>

              <!-- trending ads -->
              <li 
              {% if 'trending-ads' in request.path %}
                    class="nav-item active"
                {% else %}
                    class="nav-item"
                {% endif %}
              >
                <a class="nav-link" href="{% url 'postad:trending_ads' %}"><i class="bi bi-fire"></i> Trending Ads</a>
              </li>

              <!-- Categories -->
                <li class="nav-item dropdown dropdown-slide @@dashboard">
                    <a
                      class="nav-link dropdown-toggle"
                      data-toggle="dropdown"
                      href="#!"
                      ><i class="bi bi-tags"></i> Categories<span><i class="fa fa-angle-down"></i></span>
                    </a>
                    <ul class="dropdown-menu">
                        {% categories as categories %}
                        <!--  -->
                        {% for category in categories %}
                        <li>
                            <a
                                class="dropdown-item @@dashboardPage"
                                href="{% url 'postad:category' pk=category.id slug=category.slug %}"
                            >
                                {{category}}
                            </a>
                        </li>
                        {% endfor %}
        
                    </ul>
                </li>

            </ul>
            <!-- end main menu -->
            <ul class="navbar-nav ml-auto mt-10">
              {% if user.is_authenticated %}

              

              <li class="nav-item">
                <a class="nav-link login-button" href="{% url 'dashboard:profile' %}">Dashboard</a>
              </li>

              <li class="nav-item">
                <a class="nav-link text-white add-button" href="{% url 'postad:create_postad' %}"><i class="fa fa-plus-circle"></i> SELL</a>
              </li>

              {% else %}
              <li class="nav-item">
                <a class="nav-link login-button" href="{% url 'accounts:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link login-button" href="{% url 'accounts:register' %}">Register</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </nav>
      </div>
    </div>
  </div>
</header>

templates/includes/left-filter-sidebar.html
{% load custom_tags %}

<div class="category-sidebar">
  <div class="widget category-list">
    <h4 class="widget-header">All Category</h4>
    <ul class="category-list">
      {% categories as categories %}
      <!--  -->
      {% for category in categories %}
      <li>
        <a href="{% url 'postad:category' pk=category.id slug=category.slug %}">{{category}} <span>{{category.adpost_count}}</span></a>
      </li>
      {% endfor %}
    </ul>
  </div>

  <div class="widget category-list">
    <h4 class="widget-header">Popular City</h4>
    <ul class="category-list">
      <li>
        <a href="{% url 'postad:city_adposts_list' city='delhi' %}"> Delhi</a>
      </li>
      <li>
        <a href="{% url 'postad:city_adposts_list' city='bangalore' %}"> Bangalore</a>
      </li>
      <li>
        <a href="{% url 'postad:city_adposts_list' city='mumbai' %}"> Mumbai</a>
      </li>
      <li>
        <a href="{% url 'postad:city_adposts_list' city='gurugram' %}"> Gurugram</a>
      </li>
      <li>
        <a href="{% url 'postad:city_adposts_list' city='kolkata' %}"> Kolkata</a>
      </li>
      <li>
        <a href="{% url 'postad:city_adposts_list' city='chennai' %}"> Chennai</a>
      </li>
    </ul>
  </div>

  <!-- form -->
  <div class="widget filter">
    <form action="{% url 'postad:filter_results' %}" method="GET">
      <h4 class="widget-header">Show Produts</h4>
      <select name="short" class="mb-5">
        <option value="">Select</option>
        <option value="Popularity">Popularity</option>
        <option value="LowestPrice">Lowest Price</option>
        <option value="HighestPrice">Highest Price</option>
      </select>

      <div class="widget price-range w-100">
        <h4 class="widget-header">Price Range</h4>
        <div class="block">
          <input
            class="range-track w-100"
            name="price"
            type="text"
            data-slider-min="1"
            data-slider-max="1000000"
            data-slider-step="1000"
            data-slider-value="[1,1000000]"
          />
          <div class="d-flex justify-content-between mt-2">
            <span class="value">₹1 - ₹10,00,000</span>
          </div>
        </div>
      </div>

      <div class="mt-5 mb-5">
        <h4 class="widget-header">By Condition</h4>
        <!--  -->
        <div class="form-check">
          <input class="form-check-input" type="radio" name="condition" id="exampleRadios1" value="Almost Like New" />
          <label class="form-check-label" for="exampleRadios1">Almost Like New</label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="condition" id="exampleRadios2" value="Brand New" />
          <label class="form-check-label" for="exampleRadios2">Brand New</label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="condition" id="exampleRadios3" value="Gently Used" />
          <label class="form-check-label" for="exampleRadios3">Gently Used</label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="condition" id="exampleRadios4" value="Heavily Used" />
          <label class="form-check-label" for="exampleRadios4">Heavily Used</label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="condition" id="exampleRadios5" value="Unboxed" />
          <label class="form-check-label" for="exampleRadios5">Unboxed</label>
        </div>
        <!--  -->
      </div>

      <button type="submit" class="btn btn-primary active w-100">Search Now</button>
    </form>
  </div>
  <!-- end form -->
</div>

templates/includes/pagination.html
{% if is_paginated %}
<div class="pagination justify-content-center">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <!-- previous -->
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
      {% endif %}
      <!-- end previous -->

      {% for i in paginator.page_range%}
      <!--  -->
      {% if page_obj.number == i %}
      <li class="page-item active"><a class="page-link" href="">{{i}}</a></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
      {% endif %}
      <!--  -->
      {% endfor %}

      <!-- next -->
      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="?page={{i}}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
      {% endif %}
      <!-- end next -->
    </ul>
  </nav>
</div>
{% endif %}

templates/includes/public-user-profile-sidebar.html
<div class="sidebar">
  <!-- User Widget -->
  
  <!-- Dashboard Links -->
  <div class="widget user-dashboard-menu">
    <ul>
        <li {% if '/public/profile/' in request.path %} class="active" {% endif %}>
        <a href="{% url 'publicprofile:public_profile' pk=profile.id %}"><i class="fa fa-user"></i>Profile</a>
      </li>

      <li {% if '/public/followers/' in request.path %} class="active" {% endif %}>
        <a href="{% url 'publicprofile:followers' pk=profile.id %}"><i class="fa fa-bolt"></i> Followers<span>{{total_followers}}</span></a>
      </li>

      <li {% if '/public/following/' in request.path %} class="active" {% endif %}>
        <a href="{% url 'publicprofile:following' pk=profile.id %}"><i class="fa fa-bolt"></i> Following<span>{{total_following}}</span></a>
      </li>
      
      <li {% if '/public/ad-posts/' in request.path %} class="active" {% endif %} >
        <a href="{% url 'publicprofile:ad_posts' pk=profile.id %}"> <i class="fa fa-list-ul" aria-hidden="true"></i>Ads <span>{{total_ads}}</span></a> 
      </li>


      <li {% if '/public/contact/' in request.path %} class="active" {% endif %}>
        <a href="{% url 'publicprofile:contact_ad_user' pk=profile.id %}"><i class="fa fa-commenting-o" aria-hidden="true"></i> Contacts</a>
      </li>


      

    </ul>
  </div>

  <!-- delete-account modal -->
  <!-- delete account popup modal start-->
  <!-- Modal -->
  <div class="modal fade" id="deleteaccount" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header border-bottom-0">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body text-center">
          <img src="images/account/Account1.png" class="img-fluid mb-2" alt="" />
          <h6 class="py-2">Are you sure you want to delete your account?</h6>
          <p>Do you really want to delete these records? This process cannot be undone.</p>
          <textarea class="form-control" name="message" id="" cols="40" rows="4" class="w-100 rounded"></textarea>
        </div>
        <div class="modal-footer border-top-0 mb-3 mx-5 justify-content-center">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-danger">Delete</button>
        </div>
      </div>
    </div>
  </div>
  <!-- delete account popup modal end-->
  <!-- delete-account modal -->
</div>

templates/includes/user-profile-sidebar.html
<div class="sidebar">
  <!-- User Widget -->
  
  <!-- Dashboard Links -->
  <div class="widget user-dashboard-menu">
    <ul>
        <li {% if '/dashboard/profile/' in request.path %} class="active" {% endif %}>
        <a href="{% url 'dashboard:profile' %}"><i class="fa fa-user"></i>Profile</a>
      </li>
      <li {% if '/dashboard/followers/' in request.path %} class="active" {% endif %}>
        <a href="{% url 'dashboard:followers' %}"><i class="fa fa-bolt"></i> Followers<span>{{total_followers}}</span></a>
      </li>

      <li {% if '/dashboard/following/' in request.path %} class="active" {% endif %} >
        <a href="{% url 'dashboard:following' %}"><i class="fa fa-bolt"></i> Following<span>{{total_followings}}</span></a>
      </li>
      
      <li {% if '/dashboard/my-ad-posts/' in request.path %} class="active" {% endif %} >
        <a href="{% url 'dashboard:my_adposts' %}"> <i class="fa fa-list-ul" aria-hidden="true"></i>My Ads <span>{{total_ads}}</span></a> 
      </li>

      <li {% if '/dashboard/bookmarks/' in request.path %} class="active" {% endif %} >
        <a href="{% url 'dashboard:bookmark_adposts' %}"><i class="fa fa-bookmark-o"></i> Favourite Ads <span>{{total_bookmarks}}</span></a>
      </li>

      <li {% if '/dashboard/contacts/' in request.path %} class="active" {% endif %}>
        <a href="{% url 'dashboard:user_contacts' %}"><i class="fa fa-commenting-o" aria-hidden="true"></i> Contacts<span>{{total_contacts}}</span></a>
      </li>

      <li {% if '/dashboard/update-profile/' in request.path %} class="active" {% endif %} >
        <a href="{% url 'dashboard:update_profile' pk=profile.id %}"><i class="fa fa-cog"></i> Settings</a>
      </li>

      <li>
        <a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a>
      </li>

      <li>
        <a href="#!" data-toggle="modal" data-target="#deleteaccount"><i class="fa fa-power-off"></i>Delete Account</a>
      </li>
    </ul>
  </div>

  <!-- delete-account modal -->
  <!-- delete account popup modal start-->
  <!-- Modal -->
  <div class="modal fade" id="deleteaccount" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header border-bottom-0">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body text-center">
          <img src="images/account/Account1.png" class="img-fluid mb-2" alt="" />
          <h6 class="py-2">Are you sure you want to delete your account?</h6>
          <p>Do you really want to delete these records? This process cannot be undone.</p>
          <textarea class="form-control" name="message" id="" cols="40" rows="4" class="w-100 rounded"></textarea>
        </div>
        <div class="modal-footer border-top-0 mb-3 mx-5 justify-content-center">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-danger">Delete</button>
        </div>
      </div>
    </div>
  </div>
  <!-- delete account popup modal end-->
  <!-- delete-account modal -->
</div>