classimax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("postad.urls")),
    path("accounts/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("public/", include("publicprofile.urls")),
    path("friends/", include("friends.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from dashboard.views import *
from friends.views import *


app_name = "dashboard"

urlpatterns = [
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("update-profile/<int:pk>/", UpdateUserProfile.as_view(), name="update_profile"),
    path("my-ad-posts/", MyAdPostView.as_view(), name="my_adposts"),
    path("bookmarks/", BookmarkAdPostView.as_view(), name="bookmark_adposts"),
    path("contacts/", ContactUserView.as_view(), name="user_contacts"),
    path("send-contact/", SendContactView.as_view(), name="send_contact"),
    path("following/", FollowingsListView.as_view(), name="following"),
    path("followers/", FollowersListView.as_view(), name="followers")

]

postad/urls.py
from django.urls import path
from postad.views import *


app_name = "postad"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("adposts/", PostAdView.as_view(), name="adposts"),
    path("post/<int:pk>/<slug:slug>/", PostAdDetailView.as_view(), name="postad_detail"),
    path("create-postad/", PostAdCreateView.as_view(), name="create_postad"),
    path("update/<int:pk>/<slug:slug>/", UpdatePostAdView.as_view(), name="update_postad"),
    path("delete/<int:pk>/<slug:slug>", DeletePostAdView.as_view(), name="delete_adpost"),
    path("search-results/", SearchResultView.as_view(), name="search_results"),
    path("filter-results/", FilterResultView.as_view(), name="filter_results"),
    path("category/<int:pk>/<slug:slug>/", CategoryPostAdView.as_view(), name="category"),
    path("adposts/<str:city>/", CityAdPostListView.as_view(), name="city_adposts_list"),
    path("report/<int:pk>/", ReportAdCreateView.as_view(), name="report"),
    path("recent-visit-ads/", RecentVisitAdPostView.as_view(), name="recent_visit_ads"),
    path("trending-ads/", TrendingAdsViewList.as_view(), name="trending_ads"),
    path("following-users-ads/", FollowingUsersAdsListView.as_view(), name="following_users_ads"),
    path("about-us/", AboutUsView.as_view(), name="about_us"),
    path("terms-and-consitions/", TermsAndConditionsView.as_view(), name="terms_and_conditions"),
]

publicprofile/urls.py
from django.urls import path
from publicprofile.views import *

app_name = "publicprofile"

urlpatterns = [
    path("profile/<int:pk>/", PublicUserProfileView.as_view(), name="public_profile"),
    path("ad-posts/<int:pk>/", AdPostPublicView.as_view(), name="ad_posts"),
    path("contact/<int:pk>/", ContactAdUserView.as_view(), name="contact_ad_user"),
    path("following/<int:pk>/", FollowingsDetailView.as_view(), name="following"),
    path("followers/<int:pk>/", FollowersDetailView.as_view(), name="followers"),
    path("users/", UsersListView.as_view(), name="user_list")
]

dashboard/views.py
from django.views.generic import TemplateView, CreateView, DetailView, ListView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.forms import RegisterForm, UserProfileUpdateForm, CreateContactForm
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User
from django.conf import settings
from accounts.models import Account, ContactUser
from postad.models import PostAD, Bookmark
from friends.models import Follow
from django.contrib.auth import get_user_model
User = get_user_model()



class UserProfileView(LoginRequiredMixin, ListView):
    model = PostAD
    template_name = "dashboard/profile.html"
    context_object_name = "posts"

    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(*kwargs)
        context["profile"] = self.request.user
        context["total_followers"] = Follow.objects.filter(following=self.request.user).count()
        context["total_followings"] = Follow.objects.filter(user=self.request.user).count()
        context["total_ads"] = PostAD.objects.filter(user=self.request.user).count()
        context["total_bookmarks"] = Bookmark.objects.filter(user=self.request.user).count()
        context["total_contacts"] = ContactUser.objects.filter(receiver_user=self.request.user).count()
        return context
    
    def get_queryset(self):
        return PostAD.objects.filter(user=self.request.user).order_by("-id")


class UpdateUserProfile(LoginRequiredMixin, UpdateView):
    model = Account
    template_name = "dashboard/update-user-profile.html"
    form_class = UserProfileUpdateForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super(UpdateUserProfile, self).form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy("dashboard:profile")

    def get_context_data(self, **kwargs):
        context = super(UpdateUserProfile, self).get_context_data(*kwargs)
        context["profile"] = self.request.user
        context["total_followers"] = Follow.objects.filter(following=self.request.user).count()
        context["total_followings"] = Follow.objects.filter(user=self.request.user).count()
        context["total_ads"] = PostAD.objects.filter(user=self.request.user).count()
        context["total_bookmarks"] = Bookmark.objects.filter(user=self.request.user).count()
        context["total_contacts"] = ContactUser.objects.filter(receiver_user=self.request.user).count()
        return context
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object != request.user:
            return HttpResponseRedirect("/")
        
        return super(UpdateUserProfile, self).get(request, *args, **kwargs)


class MyAdPostView(LoginRequiredMixin, ListView):
    model = PostAD
    template_name = "dashboard/my-ad-post.html"
    context_object_name = "adposts"
    paginate_by = 9

    def get_queryset(self):
        return PostAD.objects.filter(user=self.request.user).order_by("-id")
    
    def get_context_data(self, **kwargs):
        context = super(MyAdPostView, self).get_context_data(**kwargs)
        context["profile"] = self.request.user
        context["total_followers"] = Follow.objects.filter(following=self.request.user).count()
        context["total_followings"] = Follow.objects.filter(user=self.request.user).count()
        context["total_ads"] = PostAD.objects.filter(user=self.request.user).count()
        context["total_bookmarks"] = Bookmark.objects.filter(user=self.request.user).count()
        context["total_contacts"] = ContactUser.objects.filter(receiver_user=self.request.user).count()
        return context


class BookmarkAdPostView(LoginRequiredMixin, ListView):
    model = Bookmark
    template_name = "dashboard/bookmark-ad-posts.html"
    context_object_name = "bookmarks"
    paginate_by = 9

    def get_queryset(self):
        return Bookmark.objects.filter(user=self.request.user).order_by("-id")

    def get_context_data(self, **kwargs):
        context = super(BookmarkAdPostView, self).get_context_data(**kwargs)
        context["profile"] = self.request.user
        context["total_followers"] = Follow.objects.filter(following=self.request.user).count()
        context["total_followings"] = Follow.objects.filter(user=self.request.user).count()
        context["total_ads"] = PostAD.objects.filter(user=self.request.user).count()
        context["total_bookmarks"] = Bookmark.objects.filter(user=self.request.user).count()
        context["total_contacts"] = ContactUser.objects.filter(receiver_user=self.request.user).count()
        return context


class ContactUserView(LoginRequiredMixin, ListView):
    model = ContactUser
    template_name = "dashboard/contacts.html"
    context_object_name = "contacts"
    paginate_by = 9

    def get_queryset(self):
        return ContactUser.objects.filter(receiver_user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(ContactUserView, self).get_context_data(**kwargs)
        context["profile"] = self.request.user
        context["total_followers"] = Follow.objects.filter(following=self.request.user).count()
        context["total_followings"] = Follow.objects.filter(user=self.request.user).count()
        context["total_ads"] = PostAD.objects.filter(user=self.request.user).count()
        context["total_bookmarks"] = Bookmark.objects.filter(user=self.request.user).count()
        context["total_contacts"] = ContactUser.objects.filter(receiver_user=self.request.user).count()
        return context


class SendContactView(LoginRequiredMixin, CreateView):
    model = ContactUser
    template_name = "dashboard/send-contact.html"
    form_class = CreateContactForm

    def get_context_data(self, **kwargs):
        context = super(SendContactView, self).get_context_data(**kwargs)
        context["profile"] = self.request.user
        return context


class FollowingsListView(LoginRequiredMixin, ListView):
    model = Follow
    template_name = "dashboard/following.html"
    context_object_name = "followings"

    def get_queryset(self):
        return Follow.objects.filter(user=self.request.user).order_by("-date")
    
    def get_context_data(self, **kwargs):
        context = super(FollowingsListView, self).get_context_data(**kwargs)
        context["profile"] = self.request.user
        context["total_followers"] = Follow.objects.filter(following=self.request.user).count()
        context["total_followings"] = Follow.objects.filter(user=self.request.user).count()
        context["total_ads"] = PostAD.objects.filter(user=self.request.user).count()
        context["total_bookmarks"] = Bookmark.objects.filter(user=self.request.user).count()
        context["total_contacts"] = ContactUser.objects.filter(receiver_user=self.request.user).count()
        return context


class FollowersListView(LoginRequiredMixin, ListView):
    model = Follow
    template_name = "dashboard/followers.html"
    context_object_name = "followers"

    def get_queryset(self):
        return Follow.objects.filter(following=self.request.user).order_by("-date")
    
    def get_context_data(self, **kwargs):
        context = super(FollowersListView, self).get_context_data(**kwargs)
        context["profile"] = self.request.user
        context["total_followers"] = Follow.objects.filter(following=self.request.user).count()
        context["total_followings"] = Follow.objects.filter(user=self.request.user).count()
        context["total_ads"] = PostAD.objects.filter(user=self.request.user).count()
        context["total_bookmarks"] = Bookmark.objects.filter(user=self.request.user).count()
        context["total_contacts"] = ContactUser.objects.filter(receiver_user=self.request.user).count()
        return context

templates/dashboard/bookmark-ad-posts.html
{% extends "base.html" %}
<!--  -->
<!--  -->

{% block content %}

<section class="page-title">
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2 text-center">
        <!-- Title text -->
        <h3>Dashboard</h3>
      </div>
    </div>
  </div>
</section>

<!-- arunesh -->

<section class="dashboard section">
  <!-- Container Start -->
  <!-- <div class="container"> -->
  <div style="width: 85%; margin: auto">
    <!-- Row Start -->
    <div class="row">
      <div class="col-lg-3">{% include "includes/user-profile-sidebar.html" %}</div>
      <div class="col-lg-9">
        <div class="widget dashboard-container my-adslist">
          <h2 class="mb-5">{{total_bookmarks}} Favourite Ads</h2>
          <!-- table -->
          {% if bookmarks %}
          <div class="table-responsive">
            <table class="table product-dashboard-table">
              <thead>
                <tr>
                  <th>IMAGE</th>
                  <th>TITLE</th>
                  <th>STATUS</th>
                  <th>DATE</th>
                  <th class="text-center">VISIT</th>
                </tr>
              </thead>
              <tbody>
                {% for bookmark in bookmarks %}
                <tr>
                  <!-- image -->
                  <td class="product-thumb p-1 w-15" style="min-width: 150px">
                    <img src="{{bookmark.post.image1.url}}" alt="image description" width="100px" height="100px" style="border-radius: 10%" />
                  </td>

                  <!-- title -->
                  <td class="product-details w-45" style="min-width: 250px">
                    <h3 class="title ml-1 mr-2" style="font-weight: bold">
                      <a href="{% url 'postad:postad_detail' pk=bookmark.post.id slug=bookmark.post.slug %}">{{bookmark.post.title}}</a>
                    </h3>
                  </td>

                  <!-- status -->
                  <td class="product-details w-10" style="min-width: 100px">
                    {% if not post.sold %}
                    <span class="status active">Active</span>
                    {% else %}
                    <span class="status" style="color: red">Sold</span>
                    {% endif %}
                  </td>

                  <!-- date -->
                  <td class="product-details w-10" style="min-width: 120px">
                    <p>{{bookmark.save_date|date:'d-M-o'}}</p>
                  </td>

                  <!-- visit -->
                  <td class="action w-10" data-title="Action" style="min-width: 200px">
                    <div class="">
                      <ul class="list-inline justify-content-center">
                        <li class="list-inline-item">
                          <a
                            data-toggle="tooltip"
                            data-placement="top"
                            title="View"
                            class="view"
                            href="{% url 'postad:postad_detail' pk=bookmark.post.id slug=bookmark.post.slug %}"
                          >
                            <i class="fa fa-eye"></i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a data-toggle="tooltip" data-placement="top" title="Delete" class="delete" href="#">
                            <i class="fa fa-trash"></i>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          {% else %}
          <h5 style="color: red">☹️ You don't have any bookmark post.</h5>
          {% endif %}
          <!-- end table -->
        </div>

        <!-- pagination -->
        {% include "includes/pagination.html" %}
        <!-- pagination -->
      </div>
    </div>
    <!-- Row End -->
  </div>
  <!-- Container End -->
</section>

{% endblock %}

templates/dashboard/contacts.html
{% extends "base.html" %}
<!--  -->
<!--  -->

{% block content %}

<section class="page-title">
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2 text-center">
        <!-- Title text -->
        <h3>Dashboard</h3>
      </div>
    </div>
  </div>
</section>

<!-- arunesh -->

<section class="dashboard section">
  <!-- Container Start -->
  <!-- <div class="container"> -->
  <div style="width: 85%; margin: auto">
    <!-- Row Start -->
    <div class="row">
      <div class="col-lg-3">{% include "includes/user-profile-sidebar.html" %}</div>
      <div class="col-lg-9">
        <!-- Recently Favorited -->
        <div class="widget dashboard-container my-adslist">
          <h2 class="mb-5">{{total_contacts}} Contacts is there.</h2>

          <!-- table -->
          {% if contacts %}
          <div class="table-responsive">
            <table class="table product-dashboard-table">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>USER</th>
                  <th>SUBJECT</th>
                  <th>MESSAGE</th>
                  <th>DATE</th>
                </tr>
              </thead>
              <tbody>
                {% for contact in contacts %}
                <tr>
                  <!-- id -->
                  <td class="product-thumb p-1 w-10" style="min-width: 100px">{{forloop.counter}}</td>

                  <!-- user info -->
                  <td class="product-details w-20" style="min-width: 100px">
                    <h3 class="title ml-1 mr-2" style="font-weight: bold">
                      <a href="{% url 'publicprofile:public_profile' pk=contact.sender_user.id %}">
                        {{contact.sender_user.first_name}} {{contact.sender_user.last_name}}
                      </a>
                    </h3>
                  </td>

                  <!-- subject -->
                  <td class="product-details w-15" style="min-width: 100px"><span class="categories">{{contact.subject}}</span></td>

                  <!-- message -->
                  <td class="product-details w-45 p-2" style="min-width: 250px"><span class="categories">{{contact.message}}</span></td>

                  <!-- date -->
                  <td class="product-details w-10" style="min-width: 100px"><span class="categories">{{contact.date|date:'d M o'}}</span></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          {% else %}
          <h5 style="color: red">☹️ You don't have any bookmark post.</h5>
          {% endif %}
          <!-- end table -->
        </div>

        <!-- pagination -->
        {% include "includes/pagination.html" %}
        <!-- pagination -->
      </div>
    </div>
    <!-- Row End -->
  </div>
  <!-- Container End -->
</section>

{% endblock %}

templates/dashboard/followers.html
{% extends "base.html" %}
<!--  -->
<!--  -->

{% block content %}

<section class="page-title">
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2 text-center">
        <!-- Title text -->
        <h3>Dashboard</h3>
      </div>
    </div>
  </div>
</section>

<!-- arunesh -->

<section class="dashboard section">
  <!-- Container Start -->
  <!-- <div class="container"> -->
  <div style="width: 85%; margin: auto">
    <!-- Row Start -->
    <div class="row">
      <div class="col-lg-3">{% include "includes/user-profile-sidebar.html" %}</div>
      <div class="col-lg-9">
        <!-- Recently Favorited -->
        <div class="widget dashboard-container my-adslist">
          <h2 class="mb-5">{{total_followers}} Followers</h2>

          <!-- table -->
          {% if followers %}
          <div class="table-responsive">
            <table class="table product-dashboard-table">
              <thead>
                <tr>
                  <th>IMAGE</th>
                  <th class="text-center">NAME</th>
                  <th class="text-center">DATE</th>
                  <th class="text-center">VISIT</th>
                </tr>
              </thead>
              <tbody>
                {% for follower in followers %}
                <tr>
                  <!-- image -->
                  <td class="product-thumb p-1 w-25" style="min-width: 150px">
                    {% if follower.user.image %}
                    <img src="{{follower.user.image.url}}" alt="image description" width="100px" height="100px" style="border-radius: 50%" />
                    {% endif %}
                  </td>

                  <!-- name -->
                  <td class="product-details text-center w-25" style="min-width: 200px">
                    <h3 class="title ml-2" style="font-weight: bold">
                      <a href="{% url 'publicprofile:public_profile' pk=follower.user.id %}">
                        {{follower.user.first_name}} {{follower.user.last_name}}
                      </a>
                    </h3>
                  </td>

                  <!-- date -->
                  <td class="w-25" style="min-width: 150px">
                    <div class="text-center">{{follower.date|date:'d M o'}}</div>
                  </td>

                  <!-- visit profile -->
                  <td class="action w-25" data-title="Action" style="min-width: 150px">
                    <div class="text-center">
                      <ul class="list-inline justify-content-center">
                        <li class="list-inline-item">
                          <a
                            data-toggle="tooltip"
                            data-placement="top"
                            title="View"
                            class="view"
                            href="{% url 'publicprofile:public_profile' pk=follower.user.id %}"
                          >
                            <i class="fa fa-eye"></i>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          {% else %}
          <h5 style="color: red">Oop's, do not have any follower yet 😞</h5>
          {% endif %}
          <!-- end table -->
        </div>
      </div>
    </div>
    <!-- Row End -->
  </div>
  <!-- Container End -->
</section>

{% endblock %}

templates/dashboard/following.html
{% extends "base.html" %}
<!--  -->
<!--  -->

{% block content %}

<section class="page-title">
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2 text-center">
        <!-- Title text -->
        <h3>Dashboard</h3>
      </div>
    </div>
  </div>
</section>

<!-- arunesh -->

<section class="dashboard section">
  <!-- Container Start -->
  <!-- <div class="container"> -->
  <div style="width: 85%; margin: auto">
    <!-- Row Start -->
    <div class="row">
      <div class="col-lg-3">{% include "includes/user-profile-sidebar.html" %}</div>
      <div class="col-lg-9">
        <!-- Recently Favorited -->
        <div class="widget dashboard-container my-adslist">
          <h2 class="mb-5">{{total_followings}} Following</h2>

          <!-- table -->
          {% if followings %}
          <div class="table-responsive">
            <table class="table product-dashboard-table">
              <thead>
                <tr>
                  <th>IMAGE</th>
                  <th class="text-center">NAME</th>
                  <th class="text-center">DATE</th>
                  <th class="text-center">VISIT</th>
                </tr>
              </thead>
              <tbody>
                {% for following in followings %}
                <tr>
                  <!-- image -->
                  <td class="product-thumb p-1 w-25" style="min-width: 150px">
                    {% if following.following.image %}
                    <img src="{{following.following.image.url}}" alt="image description" width="100px" height="100px" style="border-radius: 50%" />
                    {% endif %}
                  </td>

                  <!-- name -->
                  <td class="product-details text-center w-25" style="min-width: 200px">
                    <h3 class="title ml-2" style="font-weight: bold">
                      <a href="{% url 'publicprofile:public_profile' pk=following.following.id %}">
                        {{following.following.first_name}} {{following.following.last_name}}
                      </a>
                    </h3>
                  </td>

                  <!-- date -->
                  <td class="w-25" style="min-width: 150px">
                    <div class="text-center">{{following.date|date:'d M o'}}</div>
                  </td>

                  <!-- visit -->
                  <td class="action w-25" data-title="Action" style="min-width: 150px">
                    <div class="text-center">
                      <ul class="list-inline justify-content-center">
                        <li class="list-inline-item">
                          <a
                            data-toggle="tooltip"
                            data-placement="top"
                            title="View"
                            class="view"
                            href="{% url 'publicprofile:public_profile' pk=following.following.id %}"
                          >
                            <i class="fa fa-eye"></i>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          {% else %}
          <h5 style="color: red">☹️ You don't have any bookmark post.</h5>
          {% endif %}
          <!-- end table -->
        </div>
      </div>
    </div>
    <!-- Row End -->
  </div>
  <!-- Container End -->
</section>

{% endblock %}

templates/dashboard/my-ad-post.html
{% extends "base.html" %}
<!--  -->

{% block content %}

<section class="page-title">
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2 text-center">
        <!-- Title text -->
        <h3>Dashboard</h3>
      </div>
    </div>
  </div>
</section>

<section class="dashboard section">
  <!-- Container Start -->
  <!-- <div class="container"> -->
  <div style="width: 85%; margin: auto">
    <!-- Row Start -->
    <div class="row">
      <div class="col-lg-3">{% include "includes/user-profile-sidebar.html" %}</div>
      <div class="col-lg-9">
        <!-- Recently Favorited -->
        <div class="widget dashboard-container my-adslist">
          <h2>{{total_ads}} My Ads</h2>
          <hr />

          <!-- table -->
          {% if adposts %}
          <div class="table-responsive">
            <table class="table product-dashboard-table">
              <thead>
                <tr>
                  <th>IMAGE</th>
                  <th>SHORT DETAILS</th>
                  <th>ACTIONS</th>
                </tr>
              </thead>
              <tbody>
                {% for post in adposts %}
                <tr>
                  <!-- image -->
                  <td class="product-thumb p-1 w-20" style="min-width: 150px">
                    <img src="{{post.image1.url}}" alt="image description" width="100px" height="100px" style="border-radius: 10%" />
                  </td>

                  <!-- ad short detail -->
                  <td class="product-details w-60" style="min-width: 400px">
                    <!-- title -->
                    <h3 class="title ml-1 mr-2" style="font-weight: bold">
                      <a href="{% url 'postad:postad_detail' pk=post.id slug=post.slug %}">{{post.title}}</a>
                    </h3>

                    <!-- category -->
                    <span class="location"><strong>Category : </strong>{{post.category.title}}</span>

                    <!-- status -->
                    {% if not post.sold %}
                    <span class="status active"><strong>Status : </strong>Active</span>
                    {% else %}
                    <span class="status" style="color: red"><strong>Status : </strong>Sold</span>
                    {% endif %}

                    <!-- views -->
                    <span class="location"><strong>Views : </strong>{{post.hits}}</span>

                    <!-- date -->
                    <span><strong>Posted on : </strong><time>{{post.publish_date|date:'d-M-o'}}</time> </span>
                  </td>

                  <!-- action -->
                  <td class="action w-20" data-title="Action" style="min-width: 200px">
                    <div class="">
                      <ul class="list-inline justify-content-center">
                        <li class="list-inline-item">
                          <a
                            data-toggle="tooltip"
                            data-placement="top"
                            title="View"
                            class="view"
                            href="{% url 'postad:postad_detail' pk=post.id slug=post.slug %}"
                          >
                            <i class="fa fa-eye"></i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a
                            data-toggle="tooltip"
                            data-placement="top"
                            title="Edit"
                            class="edit"
                            href="{% url 'postad:update_postad' pk=post.id slug=post.slug %}"
                          >
                            <i class="fa fa-pencil"></i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a
                            data-toggle="tooltip"
                            data-placement="top"
                            title="Delete"
                            class="delete"
                            href="{% url 'postad:delete_adpost' pk=post.id slug=post.slug %}"
                          >
                            <i class="fa fa-trash"></i>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          {% else %}
          <h5 style="color: red">☹️ You don't have any ad post.</h5>
          {% endif %}
          <!-- end table -->
        </div>

        <!-- pagination -->
        {% include "includes/pagination.html" %}
        <!-- pagination -->
      </div>
    </div>
    <!-- Row End -->
  </div>
  <!-- Container End -->
</section>

{% endblock %}

templates/dashboard/update-user-profile.html
{% extends "base.html" %}
<!--  -->
{% load crispy_forms_tags %}

<!--  -->

{% block content %}

<section class="page-title">
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2 text-center">
        <!-- Title text -->
        <h3>Dashboard</h3>
      </div>
    </div>
  </div>
</section>

<section class="dashboard section">
  <!-- Container Start -->
  <!-- <div class="container"> -->
  <div style="width: 85%; margin: auto">
    <!-- <div style="width: 90%; margin: auto"> -->
    <!-- Row Start -->
    <div class="row">
      <div class="col-lg-3">{% include "includes/user-profile-sidebar.html" %}</div>
      <div class="col-lg-9">
        <!-- Edit Profile Welcome Text -->
        <div class="widget welcome-message">
          <h2>Update Profile</h2>
        </div>
        <!-- Edit Personal Info -->

        <!-- profile info -->
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="widget personal-info">
              <!-- <h4 class="widget-header user">Edit Personal Information</h4> -->
              {% crispy form %}
            </div>
          </div>
        </div>
        <!-- end profile info -->
      </div>
    </div>
    <!-- Row End -->
  </div>
  <!-- Container End -->
</section>

{% endblock %}